#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

# make sure that if a program wants you to edit
# text, that Emacs is going to be there for you
export EDITOR='emacsclient'
export VISUAL=$EDITOR
export USE_EDITOR=$EDITOR
export GIT_EDITOR=$EDITOR
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
# export ANDROID_SDK_ROOT="/usr/local/share/android-sdk
export ANDROID_SDK_ROOT="$HOME/Library/Android/sdk/"
export ANDROID_HOME="$HOME/Library/Android/sdk/"

export PATH="\
/Applications/Alacritty.app/Contents/MacOS:\
/Applications/Emacs.app/Contents/MacOS/bin:\
$HOME/.deno/bin:\
$HOME/.cargo/bin:\
$HOME/golang/bin:\
$HOME/local/bin/funcs:\
$HOME/local/bin:\
$HOME/.config/yarn/global/node_modules/.bin:\
/usr/local/opt/coreutils/libexec/gnubin:\
/usr/local/opt/curl/bin:\
/usr/local/opt/texinfo/bin:\
/usr/local/opt/coreutils/libexec/gnubin:\
/usr/local/opt/python/bin:\
/usr/local/opt/curl/bin:\
/usr/local/opt/texinfo/bin:\
/usr/local/opt/go/libexec/bin:\
/usr/local/bin:$PATH"

export YQ_MACHINE="macbook"
export YQ_BLOG_DEV_MODE="false"

#source "$HOME/.vim/plugged/gruvbox/gruvbox_256palette.sh"
export GOROOT=/usr/local/opt/go/libexec
export GOBIN=$HOME/golang/bin
export SSH_KEY_PATH="~/.ssh/id_rsa"
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export GOPATH=$HOME/golang
export ROAMER_EDITOR=emacsclient
export PYENV_ROOT="$HOME/.pyenv"
export EMAIL="namy.19@gmail.com"
export ANDROID_SDK_ROOT="/usr/local/share/android-sdk"
export ANDROID_HOME=~/Library/Android/sdk

# export HOMEBREW_BUILD_FROM_SOURCE=true
# export HOMEBREW_BUILD_FROM_SOURCE=false
export XDG_CONFIG_HOME="$HOME/.config"
# export https_proxy=http://127.0.0.1:6152
# export http_proxy=http://127.0.0.1:6152
# export all_proxy=socks5://127.0.0.1:6153
# export HTTPS_PROXY=http://127.0.0.1:6152
# export HTTP_PROXY=http://127.0.0.1:6152
# export ALL_PROXY=socks5://127.0.0.1:6153

export GEM_HOME="$(brew --prefix)/opt/gems"
export GEM_PATH="$(brew --prefix)/opt/gems"

if [[ $TERM != "emacs" && $TERM != "dumb" ]]; then
  export TERM=xterm-24bit
fi

source $HOME/Dropbox/sync/sync.zsh
export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"

eval "$(rbenv init -)" && rbenv global 2.6.5

[ -s "${HOME}/.jabba/jabba.sh" ] && source "${HOME}/.jabba/jabba.sh"
jabba use adopt@1.11.0-6

eval "$(direnv hook zsh)"
eval "$(fnm env)"
