#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export PATH="$HOME/.pyenv/shims:$HOME/.pyenv/bin:/usr/local/opt/texinfo/bin:$HOME/bin:/usr/local/bin:$HOME/local/bin:$HOME/.npm-packages/bin:$HOME/.yarn/bin:/usr/local/sbin:$HOME/bin:/usr/local/bin:$HOME/local/bin:$HOME/.npm-packages/bin:$HOME/.yarn/bin:/usr/local/sbin:$HOME/bin:/usr/local/bin:$HOME/local/bin:$HOME/.npm-packages/bin:$HOME/.yarn/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$HOME/bin:$HOME/local/bin:$HOME/.npm-packages/bin:$HOME/.yarn/bin:/usr/local/sbin:$HOME/.rvm/bin:$HOME/.fzf/bin:$HOME/.rvm/bin:$HOME/.rvm/bin:$HOME/.rvm/bin:$HOME/golang/bin/:/usr/local/opt/go/libexec/bin/:$HOME/local/bin/funcs:$HOME/.fzf/bin:$HOME/.cargo/env:$HOME/.cargo/bin"

export YQ_MACHINE="macbook"

#source "$HOME/.vim/plugged/gruvbox/gruvbox_256palette.sh"
export GOROOT=/usr/local/opt/go/libexec
export GOBIN=$HOME/golang/bin
export SSH_KEY_PATH="~/.ssh/id_rsa"
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export GOPATH=$HOME/golang
export ROAMER_EDITOR=emacsclient
export PYENV_ROOT="$HOME/.pyenv"


