# -*- mode: shell-script-*-

if [[ "$TERM" == "dumb" ]]
then
    unsetopt zle
    unsetopt prompt_cr
    unsetopt prompt_subst
    if whence -w precmd >/dev/null; then
        unfunction precmd
    fi
    if whence -w preexec >/dev/null; then
        unfunction preexec
    fi
    PS1='$ '
fi

export RUST_SRC_PATH="$HOME/rust/src"

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='emacsclient'
# else
#   export EDITOR='emacsclient'
# fi

# pro cd function
jd() {
  local projDir=$(pro search $1)
  cd ${projDir}
}

# https://github.com/syl20bnr/spacemacs/wiki/Terminal
export TERM=xterm-24bit

source $HOME/Dropbox/sync/sync.zsh

source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/history-timer.zsh"
source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/sqlite-history.zsh"

alias d='cd ~/Downloads'

[ -s "${HOME}/.jabba/jabba.sh" ] && source "${HOME}/.jabba/jabba.sh"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source "${HOME}/.config/.zsh.d/.config.zsh"
source "${HOME}/.config/.zsh.d/.keybind.zsh"
source "${HOME}/.config/.zsh.d/.alias.zsh"
source "${HOME}/.config/.zsh.d/.functions.zsh"
source "${HOME}/.config/.zsh.d/.fzf.config.zsh"

# You can customize your prompt by editing ~/.p10k.zsh.
# To run Powerlevel10k configuration wizard, type 'p9k_configure'.
source ~/.p10k.zsh

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /Users/rashawnzhang/.config/yarn/global/node_modules/tabtab/.completions/serverless.zsh ]] && . /Users/rashawnzhang/.config/yarn/global/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /Users/rashawnzhang/.config/yarn/global/node_modules/tabtab/.completions/sls.zsh ]] && . /Users/rashawnzhang/.config/yarn/global/node_modules/tabtab/.completions/sls.zsh
# tabtab source for slss package
# uninstall by removing these lines or running `tabtab uninstall slss`
[[ -f /Users/rashawnzhang/.config/yarn/global/node_modules/tabtab/.completions/slss.zsh ]] && . /Users/rashawnzhang/.config/yarn/global/node_modules/tabtab/.completions/slss.zsh

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

export PATH="/usr/local/opt/ruby/bin:$PATH"

source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'
