# -*- mode: shell-script-*-

if [[ "$TERM" == "dumb" ]]
then
    unsetopt zle
    unsetopt prompt_cr
    unsetopt prompt_subst
    if whence -w precmd >/dev/null; then
        unfunction precmd
    fi
    if whence -w preexec >/dev/null; then
        unfunction preexec
    fi
    PS1='$ '
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/history-timer.zsh"
source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/sqlite-history.zsh"

source "${HOME}/.config/.zsh.d/.config.zsh"
source "${HOME}/.config/.zsh.d/.keybind.zsh"
source "${HOME}/.config/.zsh.d/.alias.zsh"
source "${HOME}/.config/.zsh.d/.functions.zsh"
source "${HOME}/.config/.zsh.d/.fzf.config.zsh"
export RUST_SRC_PATH="$HOME/rust/src"

# Preferred editor for local and remote sessions
export EDITOR='emacsclient'
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='emacsclient'
# else
#   export EDITOR='emacsclient'
# fi

# make sure that if a program wants you to edit
# text, that Emacs is going to be there for you
export USE_EDITOR=$EDITOR

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


# pro cd function
jd() {
  local projDir=$(pro search $1)
  cd ${projDir}
}

# https://github.com/syl20bnr/spacemacs/wiki/Terminal
export TERM=xterm-24bit

source $HOME/.zprezto/modules/anything/zaw/zaw.zsh